### ISSUE TITLE
How to handle SPARQL

### ISSUE THREAD

**Issue by jeff-zucker** [jeff-zucker/solid-ui-components#4]
Currently, if the user imports mashlib but not comunica in script tags, the library will use rdflib's SPARQL engine.  If both are imported, it will use comunica's remote query engine.

Some facts to consider and unknowns to track down : 

* Comunica is SPARQL 1.1. compliant, while rdflib is rather quirky when it comes to SPARQL.
* Rdflib can handle authenticated Solid fetches, comunica can't (???)
* Rdflib does and Comunica may (???) need to download all the things and then filter them so do not take advantage of e.g. wikidata's built-in query engine to filter onsite and only download relevant results.
* Rdflib is smarter about CORS and alternate data formats than Comunica

Possible future strategies :

* try first with Comunica, if get 401, load with rdflib
* always load with rdflib then dump into Comunica in-memory and run SPARQL on it

**Comment by jeff-zucker** [comment]
And I should check this out : https://github.com/RubenVerborgh/SPARQL.js

**Comment by theRealImy** [comment]
Maybe there should be a way to let the end-user configure which SPARQL engine they want to use. (since there is no perfect solution)

**Comment by jeff-zucker** [comment]
The user can already decide by which library(ies) they import in their script.  But what we'd need is something like ui:directSparql to let users specify particular sources as accessible by one engine or another.

**Comment by jeff-zucker** [comment]
Comunica now supports authenticated Solid fetches.
